# Generated by Django 3.1.1 on 2020-09-24 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptID', models.CharField(help_text='受理编号', max_length=20, null=True, verbose_name='受理编号')),
                ('leaseArea', models.CharField(help_text='租凭面积', max_length=10, verbose_name='租凭面积')),
                ('leaseHolder', models.CharField(help_text='承租人', max_length=20, verbose_name='承租人')),
                ('holderPhone', models.CharField(help_text='承租人电话', max_length=20, verbose_name='承租人电话')),
                ('holderIDType', models.IntegerField(help_text='承租人证件类型_Dict', verbose_name='承租人证件类型')),
                ('holderID', models.CharField(help_text='承租人证件号码', max_length=20, verbose_name='承租人证件号码')),
                ('leaseMoney', models.CharField(help_text='租凭金额', max_length=10, verbose_name='租凭金额')),
                ('leasePayMoney', models.CharField(help_text='缴款金额', max_length=20, null=True, verbose_name='缴款金额')),
                ('leaseFineMoney', models.FloatField(help_text='罚款金额', max_length=10, verbose_name='罚款金额')),
                ('leaseTime', models.IntegerField(help_text='租凭期限', verbose_name='租凭期限')),
                ('leaseStartTime', models.DateField(help_text='租凭开始日期', verbose_name='租凭开始日期')),
                ('leaseEndTime', models.DateField(help_text='租凭结束日期', verbose_name='租凭结束日期')),
                ('placeName', models.CharField(help_text='场所名称', max_length=20, verbose_name='场所名称')),
                ('manageWay', models.IntegerField(help_text='经营方式_Dict', verbose_name='经营方式')),
                ('arbitrationUnits', models.CharField(help_text='仲裁单位', max_length=20, verbose_name='仲裁单位')),
                ('contractNum', models.IntegerField(help_text='合同数量', verbose_name='合同数量')),
                ('quanZheng', models.BooleanField(help_text='权证是否相符', verbose_name='权证是否相符')),
                ('chanQuanXianDing', models.BooleanField(help_text='产权有无限定条件', verbose_name='产权有无限定条件')),
                ('zhengJianQiQuan', models.BooleanField(help_text='证件是否齐全', verbose_name='证件是否齐全')),
                ('yiLiuWenTi', models.BooleanField(help_text='有无遗留问题', verbose_name='有无遗留问题')),
                ('chanQuanJiuFen', models.BooleanField(help_text='有无产权纠纷', verbose_name='有无产权纠纷')),
                ('gaiBianXingZhi', models.BooleanField(help_text='是否改变性质', verbose_name='是否改变性质')),
                ('chengDanChengDan', models.BooleanField(help_text='乙方是否符合承担条件', verbose_name='乙方是否符合承担条件')),
                ('qiYueGuiDing', models.BooleanField(help_text='契约签订是否符合规定', verbose_name='契约签订是否符合规定')),
                ('shenHeWenTi', models.BooleanField(help_text='审核中有无发现问题', verbose_name='审核中有无发现问题')),
                ('otherCondition', models.TextField(help_text='其他情况', max_length=50, verbose_name='其他情况')),
                ('leaseStatus', models.IntegerField(help_text='状态_Dict', null=True, verbose_name='状态')),
                ('addUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('houseInfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house.houseinfo')),
            ],
            options={
                'verbose_name': '租凭信息',
                'verbose_name_plural': '租凭信息',
                'db_table': 'lease_info',
            },
        ),
    ]
