# Generated by Django 3.1.1 on 2020-09-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseinfo',
            name='arbitrationUnits',
            field=models.CharField(help_text='仲裁单位', max_length=20, null=True, verbose_name='仲裁单位'),
        ),
        migrations.AlterField(
            model_name='leaseinfo',
            name='holderPhone',
            field=models.CharField(help_text='承租人电话', max_length=20, null=True, verbose_name='承租人电话'),
        ),
    ]
