# Generated by Django 3.1.1 on 2020-09-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_auto_20200907_0922'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dict',
            table='dict',
        ),
        migrations.AlterModelTable(
            name='dicttype',
            table='dict_type',
        ),
    ]
