# Generated by Django 3.1.1 on 2020-09-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200926_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='authority',
            field=models.CharField(blank=True, max_length=50, verbose_name='用户权限'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='联系电话'),
        ),
    ]
