# Generated by Django 3.1.1 on 2020-09-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200927_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displayName',
            field=models.CharField(blank=True, max_length=150, verbose_name='显示名称'),
        ),
    ]
