# Generated by Django 3.1.1 on 2020-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='IDNum',
            field=models.CharField(help_text='证件号码', max_length=20, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='IDType',
            field=models.IntegerField(help_text='证件类型_Dict', verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseAdd',
            field=models.CharField(help_text='房屋坐落', max_length=30, verbose_name='房屋坐落'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseArea',
            field=models.FloatField(help_text='房屋面积', max_length=10, verbose_name='房屋面积'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseID',
            field=models.CharField(help_text='产籍号', max_length=20, verbose_name='产籍号'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseOwner',
            field=models.CharField(help_text='产权人', max_length=20, verbose_name='产权人'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseStructure',
            field=models.IntegerField(help_text='房屋结构_Dict', verbose_name='房屋结构'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseUse',
            field=models.IntegerField(help_text='房屋用途_Dict', verbose_name='房屋用途'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='landArea',
            field=models.FloatField(help_text='占地面积', max_length=10, verbose_name='占地面积'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='ownerPhone',
            field=models.CharField(blank=True, help_text='联系电话', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='propertyID',
            field=models.CharField(help_text='产权证号', max_length=20, verbose_name='产权证号'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='propertyType',
            field=models.IntegerField(help_text='产别', verbose_name='产别'),
        ),
    ]
