# Generated by Django 3.1.1 on 2020-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='realtyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(max_length=40, verbose_name='机构名称')),
                ('officeAddress', models.CharField(max_length=40, verbose_name='办公地址')),
                ('lawPerson', models.CharField(max_length=10, verbose_name='法定代表人')),
                ('vilidityDateStart', models.DateField(verbose_name='有效期开始')),
                ('vilidityDateEnd', models.DateField(verbose_name='有效期结束')),
                ('certificateText', models.CharField(max_length=10, verbose_name='证书经字')),
                ('certificateNum', models.CharField(max_length=10, verbose_name='证书号')),
                ('addedTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '房地产经纪机构',
                'verbose_name_plural': '房地产经纪机构',
            },
        ),
    ]
